In [1]:
import numpy as np
import pandas as pd

In [45]:
df = pd.read_excel('problem2.xlsx')

In [46]:
df.head()

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36
0,10,1.0,1,1,1.0,1.0,1.0,1,1.0,1.0,...,1,1.0,1,1.0,1,1.0,1.0,1,1.0,0.0
1,10,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,...,1,NaN,1,1.0,1,0.0,1.0,1,1.0,1.0
2,9,1.0,1,0,0.0,0.0,1.0,1,1.0,1.0,...,1,NaN,1,0.0,0,0.0,1.0,1,1.0,0.0
3,10,1.0,1,0,1.0,1.0,1.0,0,0.0,1.0,...,1,NaN,0,1.0,0,1.0,0.0,1,0.0,0.0
4,3,0.0,0,0,0.0,0.0,0.0,0,0.0,1.0,...,1,0.0,0,0.0,0,0.0,0.0,0,0.0,1.0

In [17]:
df.shape

(183, 38)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 38 columns):
Y        183 non-null int64
X1       179 non-null float64
X2       183 non-null int64
X3       183 non-null int64
X4       151 non-null float64
X5       181 non-null float64
X6       161 non-null float64
X7       183 non-null int64
X8       170 non-null float64
X9       179 non-null float64
X10      166 non-null float64
X11      179 non-null float64
X12      161 non-null float64
X13      179 non-null float64
X14      155 non-null float64
X15      135 non-null float64
X16      179 non-null float64
X17      152 non-null float64
X18      26 non-null float64
X19      144 non-null float64
X20      139 non-null float64
X21      94 non-null float64
X22      136 non-null float64
X23      36 non-null float64
X24      183 non-null int64
X25      36 non-null float64
X25.1    178 non-null float64
X26      166 non-null float64
X27      183 non-null int64
X28      116 non-null float64
X29      183 non-null int64
X30      151 non-null float64
X31      183 non-null int64
X32      181 non-null float64
X33      174 non-null float64
X34      183 non-null int64
X35      170 non-null float64
X36      179 non-null float64
dtypes: float64(29), int64(9)
memory usage: 54.5 KB

In [20]:
df.isnull().any()

Y        False
X1        True
X2       False
X3       False
X4        True
X5        True
X6        True
X7       False
X8        True
X9        True
X10       True
X11       True
X12       True
X13       True
X14       True
X15       True
X16       True
X17       True
X18       True
X19       True
X20       True
X21       True
X22       True
X23       True
X24      False
X25       True
X25.1     True
X26       True
X27      False
X28       True
X29      False
X30       True
X31      False
X32       True
X33       True
X34      False
X35       True
X36       True
dtype: bool

In [58]:
df.fillna(0)

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36
0,10,1.0,1,1,1.0,1.0,1.0,1,1.0,1.0,...,1,1.0,1,1.0,1,1.0,1.0,1,1.0,0.0
1,10,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,...,1,0.0,1,1.0,1,0.0,1.0,1,1.0,1.0
2,9,1.0,1,0,0.0,0.0,1.0,1,1.0,1.0,...,1,0.0,1,0.0,0,0.0,1.0,1,1.0,0.0
3,10,1.0,1,0,1.0,1.0,1.0,0,0.0,1.0,...,1,0.0,0,1.0,0,1.0,0.0,1,0.0,0.0
4,3,0.0,0,0,0.0,0.0,0.0,0,0.0,1.0,...,1,0.0,0,0.0,0,0.0,0.0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,7,0.0,1,0,0.0,0.0,0.0,0,0.0,0.0,...,1,0.0,0,0.0,0,0.0,0.0,0,0.0,1.0
179,7,0.0,0,0,0.0,0.0,1.0,0,0.0,1.0,...,0,0.0,0,0.0,0,0.0,0.0,0,0.0,1.0
180,7,0.0,1,1,1.0,0.0,0.0,1,1.0,1.0,...,1,0.0,1,1.0,1,0.0,1.0,0,1.0,1.0
181,8,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,...,1,0.0,1,1.0,1,0.0,0.0,1,1.0,1.0
182,10,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,...,1,1.0,1,1.0,1,0.0,1.0,1,1.0,1.0

In [59]:
df.head()

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36
0,10,1.0,1,1,1.0,1.0,1.0,1,1.0,1.0,...,1,1.0,1,1.0,1,1.0,1.0,1,1.0,0.0
1,10,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,...,1,NaN,1,1.0,1,0.0,1.0,1,1.0,1.0
2,9,1.0,1,0,0.0,0.0,1.0,1,1.0,1.0,...,1,NaN,1,0.0,0,0.0,1.0,1,1.0,0.0
3,10,1.0,1,0,1.0,1.0,1.0,0,0.0,1.0,...,1,NaN,0,1.0,0,1.0,0.0,1,0.0,0.0
4,3,0.0,0,0,0.0,0.0,0.0,0,0.0,1.0,...,1,0.0,0,0.0,0,0.0,0.0,0,0.0,1.0

In [61]:
df.corr()

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36
Y,1.000000,0.395223,0.425329,0.395958,0.425269,0.359483,0.387906,0.333072,0.376576,0.230399,...,0.252454,0.176833,0.333072,0.425269,0.395958,0.359483,0.162615,0.350800,0.376576,0.205993
X1,0.395223,1.000000,0.290027,0.175756,0.353093,0.236690,0.249078,0.258017,0.157175,0.268614,...,0.248107,0.014200,0.258017,0.353093,0.175756,0.236690,0.141912,0.363855,0.157175,0.079598
X2,0.425329,0.290027,1.000000,0.412841,0.374077,0.228198,0.256584,0.422360,0.382905,0.063228,...,0.271775,0.032187,0.422360,0.374077,0.412841,0.228198,0.272120,0.383106,0.382905,0.119681
X3,0.395958,0.175756,0.412841,1.000000,0.561647,0.187424,0.238899,0.549708,0.392744,0.106589,...,0.237810,0.201960,0.549708,0.561647,1.000000,0.187424,0.366591,0.354832,0.392744,0.175684
X4,0.425269,0.353093,0.374077,0.561647,1.000000,0.418186,0.224018,0.521854,0.320952,0.195696,...,0.443168,0.276177,0.521854,1.000000,0.561647,0.418186,0.188313,0.519240,0.320952,0.197305
X5,0.359483,0.236690,0.228198,0.187424,0.418186,1.000000,0.228475,0.343334,0.173201,0.109595,...,0.215388,0.199752,0.343334,0.418186,0.187424,1.000000,0.242114,0.333216,0.173201,0.181531
X6,0.387906,0.249078,0.256584,0.238899,0.224018,0.228475,1.000000,0.259459,0.251117,0.293145,...,0.108288,0.120207,0.259459,0.224018,0.238899,0.228475,0.196554,0.180485,0.251117,0.090227
X7,0.333072,0.258017,0.422360,0.549708,0.521854,0.343334,0.259459,1.000000,0.441889,0.108816,...,0.256835,0.084985,1.000000,0.521854,0.549708,0.343334,0.396718,0.450766,0.441889,0.282057
X8,0.376576,0.157175,0.382905,0.392744,0.320952,0.173201,0.251117,0.441889,1.000000,0.059464,...,0.134554,0.080796,0.441889,0.320952,0.392744,0.173201,0.294331,0.286464,1.000000,0.308522
X9,0.230399,0.268614,0.063228,0.106589,0.195696,0.109595,0.293145,0.108816,0.059464,1.000000,...,0.113566,-0.031224,0.108816,0.195696,0.106589,0.109595,-0.078611,0.347053,0.059464,-0.026951
X10,0.378450,0.300136,0.318203,0.212870,0.347893,0.175375,0.193167,0.294796,0.322240,0.344322,...,0.258386,-0.062597,0.294796,0.347893,0.212870,0.175375,0.062261,0.353196,0.322240,0.072402
X11,0.230399,0.268614,0.063228,0.106589,0.195696,0.109595,0.293145,0.108816,0.059464,1.000000,...,0.113566,-0.031224,0.108816,0.195696,0.106589,0.109595,-0.078611,0.347053,0.059464,-0.026951
X12,0.387906,0.249078,0.256584,0.238899,0.224018,0.228475,1.000000,0.259459,0.251117,0.293145,...,0.108288,0.120207,0.259459,0.224018,0.238899,0.228475,0.196554,0.180485,0.251117,0.090227
X13,0.395223,1.000000,0.290027,0.175756,0.353093,0.236690,0.249078,0.258017,0.157175,0.268614,...,0.248107,0.014200,0.258017,0.353093,0.175756,0.236690,0.141912,0.363855,0.157175,0.079598
X14,0.156107,0.075308,0.047449,0.199738,0.035761,-0.066692,0.113960,0.176863,0.126648,0.070042,...,0.043924,0.065062,0.176863,0.035761,0.199738,-0.066692,0.102789,0.083301,0.126648,0.150827
X15,0.159075,0.189423,0.175358,0.186298,0.116632,0.214868,0.221752,0.247667,0.307771,0.112040,...,-0.012474,0.090326,0.247667,0.116632,0.186298,0.214868,0.228985,0.172005,0.307771,0.267962
X16,0.251962,0.270620,0.016839,0.058996,0.148475,0.120848,0.208223,0.057345,0.127416,0.151422,...,0.047678,0.189620,0.057345,0.148475,0.058996,0.120848,0.008027,0.180463,0.127416,0.065595
X17,0.387243,0.348722,0.205748,0.160387,0.277786,0.173070,0.197343,0.090562,0.038936,0.608826,...,0.227121,-0.009675,0.090562,0.277786,0.160387,0.173070,-0.022554,0.244203,0.038936,-0.114715
X18,0.477463,0.393179,0.740153,0.595010,0.730297,0.262781,0.269680,0.456832,0.583095,0.273483,...,0.334367,0.301511,0.456832,0.730297,0.595010,0.262781,0.483046,0.390095,0.583095,0.318010
X19,0.298363,0.191882,0.283562,0.261827,0.369518,0.180512,0.189229,0.355363,0.233055,0.233021,...,0.293418,0.234607,0.355363,0.369518,0.261827,0.180512,0.041311,0.581360,0.233055,-0.052493
X20,0.202006,0.115783,0.127310,0.210182,0.189095,0.194873,-0.013321,0.157377,-0.041290,0.109818,...,0.286456,0.097542,0.157377,0.189095,0.210182,0.194873,0.025335,0.249904,-0.041290,-0.055734
X21,0.379048,0.151435,0.200549,0.198133,0.317088,0.172005,0.184211,0.330654,0.276839,0.216957,...,0.330654,0.100963,0.330654,0.317088,0.198133,0.172005,0.216050,0.227619,0.276839,0.132454
X22,0.214540,0.100504,0.121233,0.223009,0.283859,0.157003,0.139770,0.283927,0.304257,0.068041,...,0.092343,0.180500,0.283927,0.283859,0.223009,0.157003,0.126410,0.231655,0.304257,-0.002279
X23,0.527705,0.170389,0.369175,0.448833,0.488645,0.298807,0.629630,0.500000,0.199481,0.685344,...,0.059761,0.276956,0.500000,0.488645,0.448833,0.298807,0.134715,0.312500,0.199481,0.120173
X24,0.425329,0.290027,1.000000,0.412841,0.374077,0.228198,0.256584,0.422360,0.382905,0.063228,...,0.271775,0.032187,0.422360,0.374077,0.412841,0.228198,0.272120,0.383106,0.382905,0.119681
X25,0.501107,0.107583,0.364938,0.517857,0.571315,0.180702,0.050252,0.472456,0.432722,-0.134005,...,0.225877,0.166667,0.472456,0.571315,0.517857,0.180702,0.270666,0.188982,0.432722,0.326823
X25.1,0.534614,0.464623,0.259394,0.395033,0.596079,0.273858,0.297811,0.393295,0.306206,0.363789,...,0.219145,0.144337,0.393295,0.596079,0.395033,0.273858,0.220357,0.410194,0.306206,0.205556
X26,0.378450,0.300136,0.318203,0.212870,0.347893,0.175375,0.193167,0.294796,0.322240,0.344322,...,0.258386,-0.062597,0.294796,0.347893,0.212870,0.175375,0.062261,0.353196,0.322240,0.072402
X27,0.252454,0.248107,0.271775,0.237810,0.443168,0.215388,0.108288,0.256835,0.134554,0.113566,...,1.000000,0.283283,0.256835,0.443168,0.237810,0.215388,0.095806,0.401515,0.134554,-0.049088
X28,0.176833,0.014200,0.032187,0.201960,0.276177,0.199752,0.120207,0.084985,0.080796,-0.031224,...,0.283283,1.000000,0.084985,0.276177,0.201960,0.199752,0.119061,0.152090,0.080796,-0.097557
X29,0.333072,0.258017,0.422360,0.549708,0.521854,0.343334,0.259459,1.000000,0.441889,0.108816,...,0.256835,0.084985,1.000000,0.521854,0.549708,0.343334,0.396718,0.450766,0.441889,0.282057
X30,0.425269,0.353093,0.374077,0.561647,1.000000,0.418186,0.224018,0.521854,0.320952,0.195696,...,0.443168,0.276177,0.521854,1.000000,0.561647,0.418186,0.188313,0.519240,0.320952,0.197305
X31,0.395958,0.175756,0.412841,1.000000,0.561647,0.187424,0.238899,0.549708,0.392744,0.106589,...,0.237810,0.201960,0.549708,0.561647,1.000000,0.187424,0.366591,0.354832,0.392744,0.175684
X32,0.359483,0.236690,0.228198,0.187424,0.418186,1.000000,0.228475,0.343334,0.173201,0.109595,...,0.215388,0.199752,0.343334,0.418186,0.187424,1.000000,0.242114,0.333216,0.173201,0.181531
X33,0.162615,0.141912,0.272120,0.366591,0.188313,0.242114,0.196554,0.396718,0.294331,-0.078611,...,0.095806,0.119061,0.396718,0.188313,0.366591,0.242114,1.000000,0.108653,0.294331,0.139178
X34,0.350800,0.363855,0.383106,0.354832,0.519240,0.333216,0.180485,0.450766,0.286464,0.347053,...,0.401515,0.152090,0.450766,0.519240,0.354832,0.333216,0.108653,1.000000,0.286464,0.007089
X35,0.376576,0.157175,0.382905,0.392744,0.320952,0.173201,0.251117,0.441889,1.000000,0.059464,...,0.134554,0.080796,0.441889,0.320952,0.392744,0.173201,0.294331,0.286464,1.000000,0.308522
X36,0.205993,0.079598,0.119681,0.175684,0.197305,0.181531,0.090227,0.282057,0.308522,-0.026951,...,-0.049088,-0.097557,0.282057,0.197305,0.175684,0.181531,0.139178,0.007089,0.308522,1.000000

In [62]:
Y = df['Y']

In [63]:
Y.head()

0    10
1    10
2     9
3    10
4     3
Name: Y, dtype: int64

In [64]:
X = df.drop(['Y'],axis = 1)
X

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36
0,1.0,1,1,1.0,1.0,1.0,1,1.0,1.0,1.0,...,1,1.0,1,1.0,1,1.0,1.0,1,1.0,0.0
1,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,1.0,...,1,NaN,1,1.0,1,0.0,1.0,1,1.0,1.0
2,1.0,1,0,0.0,0.0,1.0,1,1.0,1.0,1.0,...,1,NaN,1,0.0,0,0.0,1.0,1,1.0,0.0
3,1.0,1,0,1.0,1.0,1.0,0,0.0,1.0,1.0,...,1,NaN,0,1.0,0,1.0,0.0,1,0.0,0.0
4,0.0,0,0,0.0,0.0,0.0,0,0.0,1.0,0.0,...,1,0.0,0,0.0,0,0.0,0.0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,0.0,1,0,NaN,0.0,0.0,0,0.0,0.0,0.0,...,1,NaN,0,NaN,0,0.0,0.0,0,0.0,1.0
179,0.0,0,0,0.0,0.0,1.0,0,0.0,1.0,1.0,...,0,0.0,0,0.0,0,0.0,0.0,0,0.0,1.0
180,0.0,1,1,1.0,0.0,NaN,1,1.0,1.0,NaN,...,1,NaN,1,1.0,1,0.0,1.0,0,1.0,1.0
181,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,1.0,...,1,NaN,1,1.0,1,0.0,0.0,1,1.0,1.0
182,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,1.0,...,1,1.0,1,1.0,1,0.0,1.0,1,1.0,1.0

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.30,random_state =4)

In [67]:
X_train.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36
108,1.0,1,1,1.0,0.0,NaN,0,1.0,0.0,1.0,...,1,0.0,0,1.0,1,0.0,1.0,0,1.0,1.0
153,1.0,1,1,1.0,1.0,1.0,1,1.0,1.0,1.0,...,1,NaN,1,1.0,1,1.0,0.0,1,1.0,1.0
25,1.0,1,1,1.0,0.0,1.0,1,1.0,1.0,1.0,...,1,NaN,1,1.0,1,0.0,1.0,1,1.0,0.0
152,1.0,1,1,1.0,0.0,1.0,1,NaN,1.0,1.0,...,1,0.0,1,1.0,1,0.0,1.0,1,NaN,0.0
37,1.0,1,1,1.0,1.0,1.0,1,1.0,1.0,1.0,...,1,1.0,1,1.0,1,1.0,0.0,1,1.0,1.0

In [68]:
from sklearn.linear_model import LinearRegression

In [69]:
model = LinearRegression(X_train,y_train)

In [70]:
model.fit(X_test,y_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').